---
- hosts: 172.31.15.27
  become: yes
  tasks:
     - name: i want install tree
       apt:
          name: tree
          state: present

     - name: i want install wget 
       apt:
          name: wget
          state: present


       